image: python:3.12.2

variables:
  POSTGRES_DB: rent_bike
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password

stages:
  - test
  - deploy

pytest:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest --cov=. 

deploy:
  stage: deploy
  script:
    - docker-compose up -d 
  only:
    - master 
