version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rent_bike
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  redis:
    image: redis:alpine

volumes:
  postgres_data: